version: '3.8'

services:
  postgres:
    image: postgres:14
    container_name: devjobs-postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: devjobs
      POSTGRES_PASSWORD: dev#jobs@2025
      POSTGRES_DB: devjobs
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: